export const FEATURES = {
    DAILY_WORK_REPORT: "WRK_RPRT",
    EMAIL_NOTIFICATIONS: "EMAIL_NOTI",
    DOCUMENT_STORAGE: "DCMT_STRGE",
    LEAVES_MODULE: "LVE_MNGMT",
    EMPLOYEE_SEARCH: "EMP_SEARCH",
    EMPLOYEE_MANAGEMENT: "EMP_MNGMT",
    ADMIN_LIMIT: "ADMIN_LIMIT",
};
